### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wayne930242** [g0v/askkk#8]
新增的問題沒有出現在集氣頁；登入好像也有問題，按登入後一直跳回原本頁面沒有登入，直到按了發問才忽然出現已登入的狀態。

**Comment by walkingice** [comment]
也許是右上角的狀態沒有正確更新？我剛剛用 Fx 嘗試 login，必須要重開一次頁面才會看見登入的狀態

**Comment by pm5** [comment]
fixed by @soidid

**Comment by pm5** [comment]
and 新問題會出現在「集氣」的「最新」or 「全部」
